Introduction to Tensors

In [ ]:
import tensorflow as tf
tf.__version__

'2.5.0'

In [ ]:
# Creating Tensors with `tf.constant()` #Scalar => Quantity
scalar=tf.constant(22)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=22>

In [ ]:
# Checking the number of dimensions of a tensor `ndim => Number of dimensions`
scalar.ndim

0

In [ ]:
# Creating a vector #Vector => Quantity that has magnitue and direction
vector = tf.constant([8,22])
print(vector)
print("Dimensions of vector::",vector.ndim)

tf.Tensor([ 8 22], shape=(2,), dtype=int32)
Dimensions of vector:: 1


In [ ]:
# Checking with a matrix #Matrix=> Rectangular array of numbers
matrix = tf.constant([[4,22],[8,22]])
print(matrix)
print("Dimensions of matrix::",matrix.ndim)

tf.Tensor(
[[ 4 22]
 [ 8 22]], shape=(2, 2), dtype=int32)
Dimensions of matrix:: 2


In [ ]:
matrix = tf.constant([[1,3,4],
                      [3,0,4]])
print(matrix)
print(matrix.shape)
print("Dimensions of 2*3 ::",matrix.ndim) 

tf.Tensor(
[[1 3 4]
 [3 0 4]], shape=(2, 3), dtype=int32)
(2, 3)
Dimensions of 2*3 :: 2


###Properties of tensor

1.Name

2.Shape

``` tf.shape```

    The shape of a tensor is the number of elements in each dimension. i.e. length of each dimension

        m*n (m=no of rows & n=no. of columns for 2 dimensional)

3. Rank
    No of tensor dimension
    
    ```tf.ndim```

        0-Dimensional tensor => scalar

        1-Dimensional tensor => vector

        2-Dimensional tensor => matrix

        3-Dimensional tensor => cuboid

        n-Dimensional tensor =>  n*n*......*n



3.Axis or Dimension
    Dimension => No of axes (i.e. if [[[1]]] to access this I will need 3 indexes thus it has dimension of 3.)

    QUICK TIP : the length of shape is the dimension
 4. Size 
   
   ```tf.size```

        Total number of elements in tensor m*n*o


Links to resources:
https://www.gsrikar.com/2017/06/what-is-tensor-rank-and-tensor-shape.html

https://www.kdnuggets.com/2018/05/wtf-tensor.html

In [ ]:
# Creating Tensors with tf.Variable

v = tf.Variable([10,22])
v[0].assign(2)
v


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 2, 22], dtype=int32)>

In [ ]:
# Check if you can use assign() with tf.constant
c = tf.constant(5)
#c.assign(2) # It doesn't exist because it is immutable

In [ ]:
# Creating random tensors =>. Tensors of arbitrary size with random numbers
random_tensor_1 = tf.random.Generator.from_seed(22)
# Seeds are used to generate Pseudo-random numbers
random_tensor_1.normal(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7531523 ,  2.0261486 ],
       [-0.06997604,  0.85445154],
       [ 0.1175475 ,  0.03493892]], dtype=float32)>

In [ ]:
random_tensor_1.normal(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.0798842 , -1.9064091 ],
       [ 1.3262484 ,  1.3250229 ],
       [-0.5515071 , -0.03015503]], dtype=float32)>

In [ ]:
random_tensor_2 = tf.random.Generator.from_seed(22)
random_tensor_2.normal(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7531523 ,  2.0261486 ],
       [-0.06997604,  0.85445154],
       [ 0.1175475 ,  0.03493892]], dtype=float32)>

This class `tf.random.Generato`r uses a `tf.Variable` to manage its internal state. Every time random numbers are generated, the state of the generator will change.

Meaning you if you run it twice the result will vary. (Test it)

If the generator is seeded (e.g. created via Generator.from_seed), the random numbers will be determined by the seed, even though different replicas get different numbers. One can think of a random number generated on a replica as a hash of the replica ID and a "master" random number that may be common to all replicas. Hence, the whole system is still deterministic.


Link to resource: https://www.tensorflow.org/api_docs/python/tf/random/Generator

## Shuffling the order of elements in tensor

Why?

To bring variety in our dataset. 

What if the first `n` dataset is all one, the model will learn about only those.

In [ ]:
not_shuffled = tf.constant([[1,2,3],[4,5,6]])
not_shuffled.ndim

2

In [ ]:
# Global seed
tf.random.set_seed(42)
# Operation seed
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [1, 2, 3]], dtype=int32)>

###tf.random.set_seed

Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

Its interactions with operation-level seeds is as follows:

* If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.

* If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.

* If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.

* If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.


Link to resource: https://www.tensorflow.org/api_docs/python/tf/random/set_seed


## Other ways to make tensors

In [ ]:
# Tensor of all ones 
t = tf.ones([1,7])
t

<tf.Tensor: shape=(1, 7), dtype=float32, numpy=array([[1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Tensor of all zeros 
t = tf.zeros([1,7])
t

<tf.Tensor: shape=(1, 7), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# From numpy arrays
import numpy as np

np_array = np.arange(1,10,)
print(np_array)
# matrix are of capitalized
X = tf.constant(np_array,shape=(3,3))
# lowercase for vector 
x = tf.constant(np_array,shape=(9))

[1 2 3 4 5 6 7 8 9]


Numpy arrays vs Tensors 

Tensors can run on GPU (much faster for numerical computing)

### Tensor Operations

Note : Opeartions are broadcasted , meaning addition and subsctration will be done for each tensor element

In [ ]:
# +, - , / , * 

t = tf.constant([[2,4],[6,8]])
t+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 14],
       [16, 18]], dtype=int32)>

In [ ]:
t-2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 2],
       [4, 6]], dtype=int32)>

In [ ]:
t/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

In [ ]:
t*2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  8],
       [12, 16]], dtype=int32)>

In [ ]:
# We can also use built-in tensor flow functions
tf.multiply(t,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  8],
       [12, 16]], dtype=int32)>

Using Tensor methods on GPU/TPU might be fast.

In [ ]:
# Matrix multiplication using '@' in python
t @ t

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[28, 40],
       [60, 88]], dtype=int32)>

In [ ]:
tf.matmul(t,t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[28, 40],
       [60, 88]], dtype=int32)>

In [ ]:
# Transpose 
t,tf.transpose(t)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 4],
        [6, 8]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 6],
        [4, 8]], dtype=int32)>)

In [ ]:
# Reshape
t,tf.reshape(t,shape=(4))

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 4],
        [6, 8]], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8], dtype=int32)>)

Changing Tensor Data types

In [ ]:
# Create a new tensor with default datatype (float32)

B = tf.constant([2.2,1.8])
B.dtype

tf.float32

In [ ]:
# Changing from float32 to float16 (Reduced Precision)

D= tf.cast(B,dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2.2, 1.8], dtype=float16)>

In [ ]:
E = tf.cast(B,dtype=tf.int32)
E

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 1], dtype=int32)>

In [ ]:
# Tensor Aggregration (min,max,abs)

# TF puts reduce_ in its aggregation function
D = tf.constant([-7.10,-10])
D

# Absolute value
tf.abs(D)

# Min
tf.reduce_min(D)

# Max
tf.reduce_max(D)
# Mean
tf.reduce_mean(D)
# Sum
tf.reduce_sum(D)

# Variance
tf.math.reduce_variance(D)

# S.D.
tf.math.reduce_std(D)


<tf.Tensor: shape=(), dtype=float32, numpy=1.45>

### Find positional Min Max

In [ ]:
# Creating a new tensor for finding poisitonal min,max
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional Max
tf.argmax(F)
np.argmax(F)

42

In [ ]:
# Find the minimum pos min

tf.argmin(F)
np.argmin(F)

16

## Squeezing a tensor ( removing all single dimentions)


In [ ]:
tf.random.set_seed(42)

G = tf.constant(tf.random.uniform(shape=[50]),shape=[1,1,1,50])
G.shape

TensorShape([1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

# One hot encoding

In [ ]:
some_list = [0,1,2,3]

# one hot encode our list of indices
# depth = no of categories

tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list,depth=4,on_value="Yes",off_value="No")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

# Finding access to GPUs

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sun Jul 18 11:57:25 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P0    26W /  70W |    224MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------